# Generated by Django 6.0.7 on 2026-07-31 08:19

import wagtail.fields
from django.db import migrations

import ai_author_forum.journals.validators


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 3), ("cta", 13), ("statistics", 17)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul", "h3"],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    2: ("wagtail.blocks.StreamBlock", [[("paragraph", 1)]], {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    5: ("wagtail.blocks.PageChooserBlock", (), {}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 5), ("title", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "validators": [
                                ai_author_forum.journals.validators.validate_public_link
                            ]
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 8), ("title", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 7), ("external", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("link", 11), ("description", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("sr_only_label", 14), ("statistics", 16)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 3), ("cta", 13), ("statistics", 17)],
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul", "h3"],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    2: ("wagtail.blocks.StreamBlock", [[("paragraph", 1)]], {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    5: ("wagtail.blocks.PageChooserBlock", (), {}),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 5), ("title", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "validators": [
                                ai_author_forum.journals.validators.validate_public_link
                            ]
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 8), ("title", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 7), ("external", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("link", 11), ("description", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 4), ("sr_only_label", 14), ("statistics", 16)]],
                        {},
                    ),
                },
            ),
        ),
    ]
