# Generated by Django 6.0.7 on 2026-07-31 08:35

import wagtail.fields
from django.db import migrations

import ai_author_forum.journals.validators


class Migration(migrations.Migration):

    dependencies = [
        ("standardpages", "0002_alter_indexpage_body_alter_standardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("cards", 18),
                    ("quote", 20),
                    ("callout", 23),
                    ("section", 27),
                    ("cta", 30),
                    ("statistics", 33),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                            ],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If left blank, the image's global alt text will be used.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("image_alt_text", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    9: ("wagtail.blocks.PageChooserBlock", (), {}),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 9), ("title", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "validators": [
                                ai_author_forum.journals.validators.validate_public_link
                            ]
                        },
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 12), ("title", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 11), ("external", 14)]],
                        {"min_num": 0, "required": False},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("description", 8), ("link", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"label": "Card", "max_num": 6, "min_num": 3},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("sr_only_label", 6), ("cards", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.TextBlock", (), {"form_classname": "title"}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 19), ("attribution", 3)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    22: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 21), ("text", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul", "h3"],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    26: ("wagtail.blocks.StreamBlock", [[("paragraph", 25)]], {}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 24), ("content", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 11), ("external", 14)]],
                        {},
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("link", 28), ("description", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (31,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("sr_only_label", 6), ("statistics", 32)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 4),
                    ("cards", 18),
                    ("quote", 20),
                    ("callout", 23),
                    ("section", 27),
                    ("cta", 30),
                    ("statistics", 33),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                            ],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If left blank, the image's global alt text will be used.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("image_alt_text", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "icon": "title", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the heading will be hidden from view and avaliable to screen-readers only.",
                            "label": "Screen reader only label",
                            "required": False,
                        },
                    ),
                    7: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic"], "required": False},
                    ),
                    9: ("wagtail.blocks.PageChooserBlock", (), {}),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 9), ("title", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "validators": [
                                ai_author_forum.journals.validators.validate_public_link
                            ]
                        },
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 12), ("title", 13)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 11), ("external", 14)]],
                        {"min_num": 0, "required": False},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 7), ("description", 8), ("link", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (16,),
                        {"label": "Card", "max_num": 6, "min_num": 3},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("sr_only_label", 6), ("cards", 17)]],
                        {},
                    ),
                    19: ("wagtail.blocks.TextBlock", (), {"form_classname": "title"}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 19), ("attribution", 3)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    22: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 21), ("text", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "template": "components/streamfield/blocks/heading2_block.html",
                        },
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul", "h3"],
                            "template": "components/streamfield/blocks/paragraph_block.html",
                        },
                    ),
                    26: ("wagtail.blocks.StreamBlock", [[("paragraph", 25)]], {}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 24), ("content", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 11), ("external", 14)]],
                        {},
                    ),
                    29: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("link", 28), ("description", 29)]],
                        {},
                    ),
                    31: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("utils.Statistic",),
                        {},
                    ),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (31,),
                        {"max_num": 3, "min_num": 3},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("sr_only_label", 6), ("statistics", 32)]],
                        {},
                    ),
                },
            ),
        ),
    ]
