# Generated by Django 6.0.7 on 2026-07-18 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("images", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRolePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_code",
                    models.SlugField(
                        max_length=64, unique=True, verbose_name="角色编码"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=120, verbose_name="角色名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="角色说明")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "is_system",
                    models.BooleanField(default=True, verbose_name="系统预设"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_role_preset",
                        to="auth.group",
                        verbose_name="Wagtail 用户组",
                    ),
                ),
            ],
            options={
                "verbose_name": "后台角色预设",
                "verbose_name_plural": "后台角色预设",
                "ordering": ["role_code"],
                "permissions": [
                    ("access_journals", "Can access journals module"),
                    ("access_article_review", "Can access article review module"),
                    ("access_placements", "Can access placements module"),
                    ("access_slots", "Can access layout slots module"),
                    ("access_static_publish", "Can access static publishing module"),
                    ("access_site_settings", "Can access site settings module"),
                    ("access_audit_log", "Can access audit log module"),
                    ("review_articles", "Can review articles"),
                    ("publish_static_site", "Can publish static site"),
                    ("rollback_static_site", "Can rollback static site"),
                    ("import_journals", "Can import journals"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("import", "导入"),
                            ("publish", "发布"),
                            ("rollback", "回滚"),
                            ("retry", "重试"),
                            ("configure", "配置变更"),
                            ("permission", "权限变更"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="动作",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failure", "失败"),
                            ("started", "进行中"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="目标类型"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="目标 ID"
                    ),
                ),
                (
                    "target_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="目标名称"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="说明")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="附加数据"),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="请求 ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="发生时间",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_author_forum_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "ordering": ["-created_at", "-pk"],
                "permissions": [("export_audit_log", "Can export audit logs")],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="AI Author Forum",
                        max_length=120,
                        verbose_name="主站名称",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="默认 SEO 标题"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(blank=True, verbose_name="默认 SEO 描述"),
                ),
                (
                    "static_output_root",
                    models.CharField(
                        default="published",
                        help_text="相对路径会以项目根目录为基准；生产环境建议通过 STATIC_PUBLISH_ROOT 配置。",
                        max_length=500,
                        verbose_name="静态输出根目录",
                    ),
                ),
                (
                    "core_navigation_locked",
                    models.BooleanField(
                        default=True,
                        help_text="开启后，核心导航只能由具备核心导航权限的管理员维护。",
                        verbose_name="锁定核心导航",
                    ),
                ),
                (
                    "default_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="默认图片",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                        verbose_name="主站 Logo",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "主站配置",
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("home", "首页"),
                            ("journals", "子期刊"),
                            ("articles", "文章"),
                            ("about", "关于"),
                        ],
                        max_length=24,
                        verbose_name="导航区域",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="显示名称")),
                ("slug", models.SlugField(max_length=120, verbose_name="唯一标识")),
                ("url", models.URLField(blank=True, verbose_name="外部链接")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "is_core",
                    models.BooleanField(
                        default=True,
                        help_text="核心导航的变更应由系统管理员执行。",
                        verbose_name="核心导航",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="navigation_items",
                        to="wagtailcore.page",
                        verbose_name="关联页面",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="site_settings.navigationitem",
                        verbose_name="父级菜单",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_items",
                        to="wagtailcore.site",
                        verbose_name="站点",
                    ),
                ),
            ],
            options={
                "verbose_name": "导航项",
                "verbose_name_plural": "导航基线",
                "ordering": ["site", "area", "sort_order", "pk"],
                "permissions": [
                    ("manage_core_navigation", "Can manage core navigation")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "area", "slug"),
                        name="site_settings_navigation_site_area_slug_uniq",
                    )
                ],
            },
        ),
    ]
