# Generated by Django 6.0.7 on 2026-07-19 16:07

from django.db import migrations

LEGACY_PERMISSIONS = {
    "publish_static_site": "Can publish static site",
    "rollback_static_site": "Can rollback static site",
}


def migrate_legacy_publish_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    database = schema_editor.connection.alias
    content_type, _ = ContentType.objects.using(database).get_or_create(
        app_label="static_publish",
        model="staticpublishjob",
    )
    canonical, _ = Permission.objects.using(database).get_or_create(
        content_type=content_type,
        codename="publish_static_site",
        defaults={"name": "Can publish and roll back static site"},
    )
    legacy_permissions = list(
        Permission.objects.filter(
            content_type__app_label="site_settings",
            codename__in=LEGACY_PERMISSIONS,
        )
    )
    if not legacy_permissions:
        return

    for group in Group.objects.filter(permissions__in=legacy_permissions).distinct():
        group.permissions.add(canonical)
        group.permissions.remove(*legacy_permissions)

    for legacy in legacy_permissions:
        for user in legacy.user_set.all():
            user.user_permissions.add(canonical)
        legacy.delete()


def restore_legacy_publish_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    content_type = ContentType.objects.get(
        app_label="site_settings",
        model="adminrolepreset",
    )
    canonical = Permission.objects.filter(
        content_type__app_label="static_publish",
        codename="publish_static_site",
    ).first()
    legacy_permissions = [
        Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )[0]
        for codename, name in LEGACY_PERMISSIONS.items()
    ]
    if canonical is None:
        return

    for group in Group.objects.filter(permissions=canonical):
        group.permissions.add(*legacy_permissions)
    for user in canonical.user_set.all():
        user.user_permissions.add(*legacy_permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0002_adminrolepreset_access_articles"),
        ("static_publish", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminrolepreset",
            options={
                "ordering": ["role_code"],
                "permissions": [
                    ("access_journals", "Can access journals module"),
                    ("access_articles", "Can access articles module"),
                    ("access_article_review", "Can access article review module"),
                    ("access_placements", "Can access placements module"),
                    ("access_slots", "Can access layout slots module"),
                    ("access_static_publish", "Can access static publishing module"),
                    ("access_site_settings", "Can access site settings module"),
                    ("access_audit_log", "Can access audit log module"),
                    ("review_articles", "Can review articles"),
                    ("import_journals", "Can import journals"),
                ],
                "verbose_name": "后台角色预设",
                "verbose_name_plural": "后台角色预设",
            },
        ),
        migrations.RunPython(
            migrate_legacy_publish_permissions,
            restore_legacy_publish_permissions,
        ),
    ]
