# Generated by Django 6.0.7 on 2026-07-23 00:15

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models

import ai_author_forum.journals.validators


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("journals", "0006_journal_hero_image_journal_hero_image_alt_and_more"),
        ("site_settings", "0003_alter_adminrolepreset_options"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("hidden", "Hidden"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "navigation group",
                "verbose_name_plural": "navigation groups",
                "ordering": ["navigation_set", "sort_order", "pk"],
                "permissions": [
                    ("archive_navigationgroup", "Can archive navigation groups"),
                    ("move_navigationgroup", "Can move navigation groups"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="navigationitem",
            options={
                "ordering": ["site", "area", "sort_order", "pk"],
                "permissions": [
                    ("manage_core_navigation", "Can manage core navigation"),
                    ("archive_navigationitem", "Can archive navigation items"),
                    ("move_navigationitem", "Can move navigation items"),
                ],
                "verbose_name": "导航项",
                "verbose_name_plural": "导航基线",
            },
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="allow_direct_access",
            field=models.BooleanField(
                default=True,
                help_text="When hidden, controls whether the generated column page remains directly accessible.",
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="navigation_items",
                to="journals.journalcategory",
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="code",
            field=models.SlugField(
                blank=True,
                help_text="Unique item code inside one navigation set. Defaults to the legacy slug when empty.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="External links must use https://.",
                validators=[ai_author_forum.journals.validators.validate_public_link],
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="internal_path",
            field=models.CharField(
                blank=True,
                help_text="Use a safe site-relative path such as /journals/ or /sections/news/.",
                max_length=500,
                validators=[ai_author_forum.journals.validators.validate_public_link],
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="open_in_new_tab",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("hidden", "Hidden"),
                    ("archived", "Archived"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("content_column", "Content column"),
                    ("wagtail_page", "Wagtail page"),
                    ("current_issue", "Current issue"),
                    ("issue_archive", "Issue archive"),
                    ("internal_path", "Internal path"),
                    ("external_url", "External URL"),
                    ("group_only", "Group only"),
                ],
                default="internal_path",
                help_text="Required for managed navigation items.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_navigation_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ContentColumnConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        validators=[
                            ai_author_forum.journals.validators.validate_controlled_rich_text
                        ],
                    ),
                ),
                ("enable_type_filter", models.BooleanField(default=True)),
                ("enable_year_filter", models.BooleanField(default=True)),
                ("page_size", models.PositiveSmallIntegerField(default=20)),
                ("seo_title", models.CharField(blank=True, max_length=160)),
                ("seo_description", models.TextField(blank=True)),
                (
                    "empty_message",
                    models.CharField(
                        default="No placed articles are currently available in this column.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_column_configs",
                        to="journals.journalcategory",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="content_column_configs",
                        to="images.customimage",
                    ),
                ),
                (
                    "navigation_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_column_config",
                        to="site_settings.navigationitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "content column configuration",
                "verbose_name_plural": "content column configurations",
            },
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Managed two-level navigation group. Leave empty only for legacy baseline navigation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="site_settings.navigationgroup",
            ),
        ),
        migrations.CreateModel(
            name="NavigationSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("main_site", "Main site"), ("journal", "Journal")],
                        default="main_site",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Use only for default journal navigation templates; never as a real journal scope.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "copied_from_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copied_navigation_sets",
                        to="site_settings.navigationset",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="navigation_sets",
                        to="journals.journal",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_navigation_sets",
                        to="wagtailcore.site",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_navigation_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "navigation set",
                "verbose_name_plural": "navigation sets",
                "ordering": ["scope", "journal_id", "site_id", "name", "pk"],
                "permissions": [
                    ("manage_main_navigation", "Can manage main site navigation"),
                    ("manage_journal_navigation", "Can manage journal navigation"),
                    (
                        "manage_navigation_template",
                        "Can manage default journal navigation templates",
                    ),
                    ("publish_navigation_changes", "Can publish navigation changes"),
                    ("delete_navigation_objects", "Can hard delete navigation objects"),
                ],
            },
        ),
        migrations.AddField(
            model_name="navigationgroup",
            name="navigation_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="site_settings.navigationset",
            ),
        ),
        migrations.AddConstraint(
            model_name="navigationset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("scope", "main_site"),
                        ("journal__isnull", True),
                        ("is_template", False),
                    ),
                    models.Q(
                        ("scope", "journal"),
                        ("journal__isnull", False),
                        ("is_template", False),
                    ),
                    models.Q(("is_template", True), ("journal__isnull", True)),
                    _connector="OR",
                ),
                name="managed_navigation_scope_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="navigationset",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_template", False), ("scope", "main_site"), ("status", "active")
                ),
                fields=("site",),
                name="one_active_main_navigation_set_per_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="navigationset",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_template", False), ("scope", "journal"), ("status", "active")
                ),
                fields=("journal",),
                name="one_active_navigation_set_per_journal",
            ),
        ),
        migrations.AddConstraint(
            model_name="navigationset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_template", True)),
                fields=("site", "name"),
                name="unique_navigation_template_name_per_site",
            ),
        ),
        migrations.AddConstraint(
            model_name="navigationgroup",
            constraint=models.UniqueConstraint(
                fields=("navigation_set", "code"),
                name="unique_navigation_group_code_per_set",
            ),
        ),
    ]
