# Generated by Django 6.0.7 on 2026-07-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0004_navigationgroup_alter_navigationitem_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationItemPathRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_path", models.CharField(max_length=500, unique=True)),
                ("new_path", models.CharField(max_length=500)),
                ("http_status", models.PositiveSmallIntegerField(default=301)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "navigation_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="path_redirects",
                        to="site_settings.navigationitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "navigation path redirect",
                "verbose_name_plural": "navigation path redirects",
                "ordering": ["old_path", "pk"],
            },
        ),
    ]
