# Generated by Django 6.0.7 on 2026-07-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0005_navigationitempathredirect"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationitem",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="navigation_items",
                to="wagtailcore.page",
                verbose_name="关联页面",
            ),
        ),
    ]
