# Generated by Django 6.0.7 on 2026-07-23 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0006_journal_hero_image_journal_hero_image_alt_and_more"),
        ("site_settings", "0006_alter_navigationitem_page"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="navigationitem",
            name="site_settings_navigation_site_area_slug_uniq",
        ),
        migrations.AddConstraint(
            model_name="navigationitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", True)),
                fields=("site", "area", "slug"),
                name="legacy_navigation_site_area_slug_uniq",
            ),
        ),
    ]
