# Generated by Django 6.0.7 on 2026-07-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0008_bootstrap_managed_navigation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navigationset",
            options={
                "ordering": ["scope", "journal_id", "site_id", "name", "pk"],
                "permissions": [
                    ("view_main_navigation", "Can view main site navigation"),
                    ("view_journal_navigation", "Can view journal navigation"),
                    (
                        "view_navigation_template",
                        "Can view default journal navigation templates",
                    ),
                    ("manage_main_navigation", "Can manage main site navigation"),
                    ("manage_journal_navigation", "Can manage journal navigation"),
                    (
                        "manage_navigation_template",
                        "Can manage default journal navigation templates",
                    ),
                    ("publish_navigation_changes", "Can publish navigation changes"),
                    ("delete_navigation_objects", "Can hard delete navigation objects"),
                ],
                "verbose_name": "navigation set",
                "verbose_name_plural": "navigation sets",
            },
        ),
    ]
