# Generated by Django 6.0.7 on 2026-07-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0009_managed_navigation_scope_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminrolepreset",
            options={
                "ordering": ["role_code"],
                "permissions": [
                    ("access_journals", "Can access journals module"),
                    ("access_articles", "Can access articles module"),
                    ("access_article_review", "Can access article review module"),
                    ("access_placements", "Can access placements module"),
                    ("access_slots", "Can access layout slots module"),
                    ("access_static_publish", "Can access static publishing module"),
                    ("access_site_settings", "Can access site settings module"),
                    ("access_audit_log", "Can access audit log module"),
                    ("review_articles", "Can review articles"),
                    ("import_journals", "Can import journals"),
                    ("import_articles", "Can import articles"),
                ],
                "verbose_name": "后台角色预设",
                "verbose_name_plural": "后台角色预设",
            },
        ),
    ]
