# Generated by Django 6.0.7 on 2026-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0011_expand_public_navigation_placeholders"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcolumnconfig",
            name="default_sort",
            field=models.CharField(
                choices=[("published_desc", "Publication date (newest first)")],
                default="published_desc",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="contentcolumnconfig",
            name="empty_behavior",
            field=models.CharField(
                choices=[
                    ("block_publish", "Block production publish"),
                    ("hide_navigation", "Hide navigation"),
                    ("editorial_message", "Show editorial message"),
                ],
                default="block_publish",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="contentcolumnconfig",
            name="minimum_publish_items",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="contentcolumnconfig",
            name="show_abstract",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contentcolumnconfig",
            name="show_authors",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contentcolumnconfig",
            name="show_open_access_badge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentcolumnconfig",
            name="template_variant",
            field=models.CharField(
                choices=[
                    ("research_list", "Research list"),
                    ("news_landing", "News landing"),
                    ("chronological", "Chronological list"),
                ],
                default="chronological",
                max_length=32,
            ),
        ),
    ]
