# Generated by Django 6.0.8 on 2026-08-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0014_relax_journal_publish_readiness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("import", "导入"),
                    ("publish", "发布"),
                    ("rollback", "回滚"),
                    ("retry", "重试"),
                    ("configure", "配置变更"),
                    ("permission", "权限变更"),
                    ("moderation", "内容审核"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="动作",
            ),
        ),
    ]
