# Generated by Django 6.0.8 on 2026-08-16 17:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleCapabilityProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_public_id", models.UUIDField(unique=True)),
                ("journal_id", models.PositiveBigIntegerField(db_index=True)),
                ("active_release", models.CharField(db_index=True, max_length=64)),
                ("approved_revision_id", models.PositiveBigIntegerField()),
                (
                    "comments_mode",
                    models.CharField(
                        choices=[
                            ("open", "开放"),
                            ("read_only", "只读"),
                            ("hidden", "隐藏"),
                        ],
                        max_length=16,
                    ),
                ),
                ("download_enabled", models.BooleanField(default=False)),
                (
                    "protected_artifact_public_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("policy_version", models.PositiveBigIntegerField()),
                ("projection_version", models.PositiveBigIntegerField()),
                ("applied_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ReaderIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("email_ciphertext", models.TextField()),
                ("email_lookup_hmac", models.CharField(max_length=64, unique=True)),
                ("email_key_version", models.PositiveSmallIntegerField()),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("display_name", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "有效"),
                            ("suspended", "已暂停"),
                            ("deleted", "已删除"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("article_public_id", models.UUIDField(db_index=True)),
                ("journal_id", models.PositiveBigIntegerField(db_index=True)),
                ("body_plaintext", models.TextField()),
                ("body_sha256", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("published", "已发布"),
                            ("hidden", "已隐藏"),
                            ("withdrawn", "已撤回"),
                            ("rejected", "已拒绝"),
                            ("spam", "垃圾"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=16,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=6, null=True
                    ),
                ),
                ("risk_labels", models.JSONField(blank=True, default=list)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("request_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replies",
                        to="reader_interactions.comment",
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_comments",
                        to="reader_interactions.comment",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="reader_interactions.readeridentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentModerationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("from_state", models.CharField(blank=True, max_length=16)),
                ("to_state", models.CharField(max_length=16)),
                ("action", models.CharField(max_length=32)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("reader", "读者"),
                            ("editor", "编辑"),
                            ("system", "系统"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor_id", models.CharField(max_length=64)),
                ("reason", models.CharField(blank=True, max_length=64)),
                ("note", models.TextField(blank=True)),
                ("command_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("request_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderation_events",
                        to="reader_interactions.comment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommentSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_public_id", models.UUIDField(db_index=True)),
                ("version", models.PositiveBigIntegerField()),
                ("object_key", models.CharField(max_length=1024, unique=True)),
                ("etag", models.CharField(max_length=128)),
                ("comment_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article_public_id", "version"),
                        name="reader_snapshot_article_version_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("email_ciphertext", models.TextField()),
                ("email_lookup_hmac", models.CharField(db_index=True, max_length=64)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("comment", "评论"),
                            ("download", "下载"),
                            ("share", "分享"),
                            ("session", "会话"),
                        ],
                        max_length=16,
                    ),
                ),
                ("return_path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "已签发"),
                            ("consumed", "已消费"),
                            ("expired", "已过期"),
                            ("superseded", "已替代"),
                            ("blocked", "已阻断"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("request_fingerprint_hmac", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["email_lookup_hmac", "purpose", "status"],
                        name="ri_challenge_email_purpose",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InteractionOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=120)),
                ("aggregate_type", models.CharField(max_length=120)),
                ("aggregate_id", models.CharField(max_length=255)),
                ("aggregate_version", models.PositiveBigIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["aggregate_type", "aggregate_id", "aggregate_version"],
                        name="reader_outbox_aggregate_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReaderActionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("share_opened", "打开分享"),
                            ("link_copied", "复制链接"),
                            ("download_granted", "签发下载"),
                            ("download_started", "开始下载"),
                        ],
                        max_length=32,
                    ),
                ),
                ("article_public_id", models.UUIDField(db_index=True)),
                (
                    "reader_public_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("outcome", models.CharField(blank=True, max_length=16)),
                ("request_id", models.UUIDField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at", "event_type"],
                        name="reader_action_created_type_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DownloadGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("article_public_id", models.UUIDField(db_index=True)),
                ("release_version", models.CharField(db_index=True, max_length=64)),
                ("artifact_public_id", models.UUIDField()),
                (
                    "token_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "已签发"),
                            ("consumed", "已消费"),
                            ("expired", "已过期"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="download_grants",
                        to="reader_interactions.readeridentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReaderSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("secret_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField()),
                ("idle_expires_at", models.DateTimeField(db_index=True)),
                ("absolute_expires_at", models.DateTimeField(db_index=True)),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("risk_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="reader_interactions.readeridentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=64)),
                ("key_hash", models.CharField(max_length=64)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="reader_interactions.readeridentity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reader", "scope", "key_hash"),
                        name="reader_idempotency_scope_key_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "垃圾"),
                            ("harassment", "骚扰"),
                            ("hate", "仇恨"),
                            ("privacy", "隐私"),
                            ("misinformation", "错误信息"),
                            ("other", "其他"),
                        ],
                        max_length=24,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("resolved", "已解决"),
                            ("dismissed", "已驳回"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="reader_interactions.comment",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comment_reports",
                        to="reader_interactions.readeridentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["comment", "status", "created_at"],
                        name="ri_report_comment_status",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("comment", "reporter"),
                        name="reader_one_open_report_per_reader",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["article_public_id", "state", "created_at", "public_id"],
                name="ri_comment_article_state",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["root", "created_at", "public_id"],
                name="ri_comment_root_created",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["reader", "created_at"],
                name="ri_comment_reader_created",
            ),
        ),
        migrations.AddIndex(
            model_name="readersession",
            index=models.Index(
                fields=["reader", "revoked_at", "absolute_expires_at"],
                name="ri_session_reader_expiry",
            ),
        ),
    ]
