# Generated by Django 6.0.8 on 2026-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="emailverificationchallenge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "issued")),
                fields=("email_lookup_hmac", "purpose"),
                name="ri_one_issued_challenge_per_purpose",
            ),
        ),
    ]
