# Generated by Django 6.0.8 on 2026-08-19 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_interactions", "0002_one_issued_challenge_per_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaderDeviceFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("user_code_hash", models.CharField(max_length=64)),
                ("origin_cookie_hash", models.CharField(max_length=64)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("comment", "评论"),
                            ("download", "下载"),
                            ("share", "分享"),
                            ("session", "会话"),
                        ],
                        max_length=16,
                    ),
                ),
                ("return_path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待确认"),
                            ("approved", "已批准"),
                            ("claimed", "已领取"),
                            ("expired", "已过期"),
                            ("cancelled", "已取消"),
                            ("superseded", "已替代"),
                            ("denied", "已拒绝"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("claimed_session_ciphertext", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_flow",
                        to="reader_interactions.emailverificationchallenge",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device_flows",
                        to="reader_interactions.readeridentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="ri_device_flow_status_expiry",
                    ),
                    models.Index(
                        fields=["origin_cookie_hash", "status"],
                        name="ri_device_flow_origin_status",
                    ),
                ],
            },
        ),
    ]
