# Generated by Django 6.0.8 on 2026-08-19 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_interactions", "0003_readerdeviceflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationchallenge",
            name="consumed_reader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumed_verification_challenges",
                to="reader_interactions.readeridentity",
            ),
        ),
        migrations.AddField(
            model_name="emailverificationchallenge",
            name="consumed_session_ciphertext",
            field=models.TextField(blank=True, null=True),
        ),
    ]
