from __future__ import annotations

import re
from dataclasses import dataclass
from io import BytesIO
from zipfile import ZIP_DEFLATED, ZipFile

from openpyxl import Workbook


@dataclass(frozen=True)
class DemoPackageSpec:
    journal_count: int = 120
    articles_per_journal: int = 100
    prefix: str = "ai-demo"
    home_feature_count: int = 24

    def validate(self):
        if not 1 <= self.journal_count <= 200:
            raise ValueError("journal_count must be between 1 and 200.")
        if not 0 <= self.articles_per_journal <= 500:
            raise ValueError("articles_per_journal must be between 0 and 500.")
        if self.home_feature_count < 0:
            raise ValueError("home_feature_count must not be negative.")
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", self.prefix):
            raise ValueError(
                "prefix must use lowercase letters, numbers, and hyphens only."
            )

    @property
    def article_count(self) -> int:
        return self.journal_count * self.articles_per_journal


JOURNAL_HEADERS = [
    "journal_name",
    "journal_name_cn",
    "slug",
    "az_group",
    "status",
    "sort_order",
    "seo_title",
    "seo_description",
    "homepage_intro",
    "static_site_path",
    "target_article_count",
    "notes",
]

ARTICLE_HEADERS = [
    "journal_slug",
    "title",
    "slug",
    "article_type",
    "authors",
    "ai_co_authors",
    "abstract",
    "keywords",
    "publication_date",
    "status",
    "sort_order",
    "is_pinned",
    "body_html",
    "build_version",
    "main_site_slot",
    "main_site_slot_name",
    "main_site_slot_title",
    "main_site_slot_summary",
    "main_site_slot_order",
    "main_site_slot_pinned",
    "journal_slot",
    "journal_slot_name",
    "journal_slot_title",
    "journal_slot_summary",
    "journal_slot_order",
    "journal_slot_pinned",
    "notes",
]

TOPICS = [
    ("Foundation Models", "AI foundation models and evaluation"),
    ("Machine Learning Systems", "deployment, governance and model operations"),
    ("AI Safety", "risk assessment and responsible frontier systems"),
    ("Human AI Collaboration", "co-authoring, review and accountability"),
    ("Computational Biology", "AI methods for biomedical discovery"),
    ("Robotics Intelligence", "embodied AI and autonomous systems"),
    ("Data Governance", "datasets, provenance and stewardship"),
    ("Scientific Computing", "AI-assisted scientific workflows"),
]


def build_demo_import_package(spec: DemoPackageSpec) -> bytes:
    spec.validate()
    output = BytesIO()
    with ZipFile(output, "w", ZIP_DEFLATED) as package:
        package.writestr("journals.xlsx", _journal_workbook(spec))
        package.writestr("articles.xlsx", _article_workbook(spec))
        package.writestr(
            "README.txt",
            (
                "AI Author Forum demo import package.\n"
                "This file is generated for repeatable CMS acceptance testing.\n"
                "Articles are imported as fixed static HTML sources and linked to "
                "the centralized static publishing workflow.\n"
            ),
        )
    return output.getvalue()


def _journal_workbook(spec: DemoPackageSpec) -> bytes:
    workbook = Workbook(write_only=True)
    sheet = workbook.create_sheet("journals")
    sheet.append(JOURNAL_HEADERS)
    for index in range(1, spec.journal_count + 1):
        topic, description = TOPICS[(index - 1) % len(TOPICS)]
        slug = f"{spec.prefix}-journal-{index:03d}"
        az_group = chr(65 + ((index - 1) % 26))
        sheet.append(
            [
                f"AI Author Forum {topic} {index:03d}",
                f"AI Author Forum {topic} {index:03d}",
                slug,
                az_group,
                "active",
                index,
                f"AI Author Forum {topic}",
                description,
                f"Curated static journal channel for {description}.",
                f"/journals/{slug}/index.html",
                spec.articles_per_journal,
                "Generated by seed_journal_demo_data.",
            ]
        )
    return _save_workbook(workbook)


def _article_workbook(spec: DemoPackageSpec) -> bytes:
    workbook = Workbook(write_only=True)
    sheet = workbook.create_sheet("articles")
    sheet.append(ARTICLE_HEADERS)
    home_remaining = spec.home_feature_count
    for journal_index in range(1, spec.journal_count + 1):
        topic, description = TOPICS[(journal_index - 1) % len(TOPICS)]
        journal_slug = f"{spec.prefix}-journal-{journal_index:03d}"
        for article_index in range(1, spec.articles_per_journal + 1):
            global_index = (
                journal_index - 1
            ) * spec.articles_per_journal + article_index
            article_slug = f"{journal_slug}-article-{article_index:03d}"
            title = f"{topic}: static AI article {article_index:03d}"
            main_slot = "home_featured" if home_remaining > 0 else ""
            main_order = global_index if home_remaining > 0 else ""
            main_pinned = home_remaining > 0
            if home_remaining > 0:
                home_remaining -= 1
            abstract = (
                f"A fixed HTML AI Article for {journal_slug}, focused on "
                f"{description}."
            )
            sheet.append(
                [
                    journal_slug,
                    title,
                    article_slug,
                    "ai_article",
                    f"Researcher {journal_index:03d}",
                    "AI Editorial Assistant",
                    abstract,
                    f"AI, {topic}, static publishing",
                    "2026-07-20T09:00:00+08:00",
                    "published",
                    article_index,
                    article_index <= 3,
                    _article_html(title, abstract, journal_slug, global_index),
                    f"demo-v{global_index:05d}",
                    main_slot,
                    "Homepage featured" if main_slot else "",
                    title if main_slot else "",
                    abstract if main_slot else "",
                    main_order,
                    main_pinned,
                    "journal_latest",
                    "Journal latest",
                    title,
                    abstract,
                    article_index,
                    article_index <= 3,
                    "Generated by seed_journal_demo_data.",
                ]
            )
    return _save_workbook(workbook)


def _article_html(title: str, abstract: str, journal_slug: str, index: int) -> str:
    return (
        "<article>"
        f"<h1>{title}</h1>"
        f"<p><strong>Journal:</strong> {journal_slug}</p>"
        f"<p>{abstract}</p>"
        "<h2>Key findings</h2>"
        "<ul>"
        f"<li>Static HTML article asset generated for acceptance row {index}.</li>"
        "<li>No runtime article detail query is required on the public site.</li>"
        "<li>Placement controls decide where this article appears after approval.</li>"
        "</ul>"
        "</article>"
    )


def _save_workbook(workbook: Workbook) -> bytes:
    stream = BytesIO()
    workbook.save(stream)
    return stream.getvalue()
