# Generated by Django 6.0.7 on 2026-07-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="page_ptr",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="news_articlepage",
                serialize=False,
                to="wagtailcore.page",
            ),
        ),
    ]
