# Generated by Django 6.0.8 on 2026-08-16 17:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0019_articlepage_public_id_contract"),
        ("journals", "0016_journal_accepts_author_submissions_and_more"),
        ("static_publish", "0006_alter_staticpublishjob_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleInteractionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comments_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "继承"),
                            ("open", "开放"),
                            ("read_only", "只读"),
                            ("hidden", "隐藏"),
                        ],
                        default="inherit",
                        max_length=16,
                    ),
                ),
                (
                    "pdf_download_policy",
                    models.CharField(
                        choices=[
                            ("inherit", "继承"),
                            ("enabled", "启用"),
                            ("disabled", "禁用"),
                        ],
                        default="inherit",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interaction_policy",
                        to="articles.articlepage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_article_interaction_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ControlPlaneOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=120)),
                ("aggregate_type", models.CharField(max_length=120)),
                ("aggregate_id", models.CharField(max_length=255)),
                ("aggregate_version", models.PositiveBigIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["aggregate_type", "aggregate_id", "aggregate_version"],
                        name="reader_cp_outbox_aggregate_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalInteractionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_comments_mode",
                    models.CharField(
                        choices=[
                            ("open", "开放"),
                            ("read_only", "只读"),
                            ("hidden", "隐藏"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("default_pdf_download_enabled", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interaction_policy",
                        to="journals.journal",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_journal_interaction_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModerationCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("comment_public_id", models.UUIDField(db_index=True)),
                ("journal_id", models.PositiveBigIntegerField(db_index=True)),
                ("article_public_id", models.UUIDField(db_index=True)),
                ("action", models.CharField(max_length=32)),
                ("expected_version", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=64)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("applied", "已应用"),
                            ("failed", "失败"),
                            ("unknown", "状态未知"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "remote_event_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("request_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reader_moderation_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProtectedArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("article_public_id", models.UUIDField(db_index=True)),
                ("approved_revision_id", models.PositiveBigIntegerField()),
                ("release_version", models.CharField(db_index=True, max_length=64)),
                ("locale", models.CharField(max_length=32)),
                (
                    "object_key",
                    models.CharField(blank=True, max_length=1024, unique=True),
                ),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("byte_size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("renderer_version", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "已请求"),
                            ("rendering", "渲染中"),
                            ("validating", "校验中"),
                            ("ready", "就绪"),
                            ("activated", "已激活"),
                            ("failed", "失败"),
                            ("retired", "已退役"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("article_public_id", "release_version", "locale"),
                        name="reader_artifact_article_release_locale_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProtectedManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=64, unique=True)),
                ("files", models.JSONField(default=list)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "待校验"),
                            ("validated", "已校验"),
                            ("failed", "失败"),
                            ("activated", "已激活"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "static_manifest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protected_manifest",
                        to="static_publish.staticmanifest",
                    ),
                ),
            ],
        ),
    ]
