# Generated by Django 6.0.8 on 2026-08-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_access", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationcommand",
            name="error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="moderationcommand",
            name="idempotency_key_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="moderationcommand",
            name="result_body",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="moderationcommand",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moderationcommand",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
