# Generated by Django 6.0.8 on 2026-08-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_access", "0002_moderationcommand_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationcommand",
            name="request_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
