# Generated by Django 6.0.7 on 2026-07-18 03:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "code",
                    models.SlugField(
                        help_text="Stable code used by templates, for example home_hero.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("section", "Section"),
                            ("journal", "Journal"),
                            ("article", "Article"),
                        ],
                        default="home",
                        max_length=20,
                    ),
                ),
                (
                    "max_items",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maximum active placements for one target in this slot.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "fill_mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Automatic fallback")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "layout slot",
                "verbose_name_plural": "layout slots",
                "ordering": ["scope", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ArticlePlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("main_site", "Main site"),
                            ("section", "Section"),
                            ("journal", "Journal"),
                            ("article", "Article"),
                        ],
                        default="main_site",
                        max_length=20,
                    ),
                ),
                (
                    "target_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Use for journal, section or article targets. Leave blank for main site slots.",
                        max_length=120,
                    ),
                ),
                (
                    "override_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title used only for this placement.",
                        max_length=255,
                    ),
                ),
                (
                    "override_summary",
                    models.TextField(
                        blank=True,
                        help_text="Optional summary used only for this placement.",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pinned items sort before normal items inside the same slot.",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="articles.articlepage",
                    ),
                ),
                (
                    "override_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="placements.layoutslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "article placement",
                "verbose_name_plural": "article placements",
                "ordering": [
                    "target_type",
                    "target_slug",
                    "slot",
                    "-is_pinned",
                    "sort_order",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slot", "article", "target_type", "target_slug"),
                        name="unique_article_placement_per_target",
                    )
                ],
            },
        ),
    ]
