# Generated by Django 6.0.7 on 2026-07-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("placements", "0004_static_page_targets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleplacement",
            name="override_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
