# Generated by Django 6.0.7 on 2026-07-21 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_articlecategoryassignment_category_and_more"),
        ("images", "0001_initial"),
        ("journals", "0005_journalcategory_journalcategorypathredirect_and_more"),
        ("placements", "0005_alter_articleplacement_override_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleplacement",
            options={
                "ordering": [
                    "target_type",
                    "target_slug",
                    "slot",
                    "-is_pinned",
                    "sort_order",
                ],
                "permissions": [
                    (
                        "view_system_categoryplacement",
                        "Can view system category placements",
                    ),
                    (
                        "retry_categoryplacement_sync",
                        "Can retry category placement sync",
                    ),
                    (
                        "manage_manual_categoryplacement",
                        "Can manage manual category placements",
                    ),
                ],
                "verbose_name": "article placement",
                "verbose_name_plural": "article placements",
            },
        ),
        migrations.RemoveConstraint(
            model_name="articleplacement",
            name="unique_article_placement_per_target",
        ),
        migrations.AddField(
            model_name="articleplacement",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="articleplacement",
            name="placement_kind",
            field=models.CharField(
                choices=[
                    ("automatic_listing", "Automatic listing"),
                    ("featured", "Featured"),
                    ("pinned", "Pinned"),
                    ("sidebar", "Sidebar"),
                ],
                default="featured",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="articleplacement",
            name="source",
            field=models.CharField(
                choices=[("system", "System"), ("manual", "Manual")],
                default="manual",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="articleplacement",
            name="target_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="journals.journalcategory",
            ),
        ),
        migrations.AddField(
            model_name="layoutslot",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="articleplacement",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="articles.articlepage",
            ),
        ),
        migrations.AlterField(
            model_name="articleplacement",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="placements",
                to="placements.layoutslot",
            ),
        ),
        migrations.AlterField(
            model_name="articleplacement",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("main_site", "Main site"),
                    ("section", "Section"),
                    ("journal", "Journal"),
                    ("article", "Article"),
                    ("search", "Search"),
                    ("category", "Category"),
                ],
                default="main_site",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="layoutslot",
            name="scope",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("section", "Section"),
                    ("journal", "Journal"),
                    ("article", "Article"),
                    ("search", "Search"),
                    ("category", "Category"),
                ],
                default="home",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="articleplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_type", "category"), _negated=True),
                fields=("slot", "article", "target_type", "target_slug"),
                name="unique_article_placement_per_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleplacement",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("placement_kind", "automatic_listing"),
                    ("source", "system"),
                    ("target_type", "category"),
                ),
                fields=("article", "target_category", "slot"),
                name="uniq_article_category_placement",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_category__isnull", False), ("target_type", "category")
                    ),
                    models.Q(
                        models.Q(("target_type", "category"), _negated=True),
                        ("target_category__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="category_target_requires_fk",
            ),
        ),
    ]
