# Generated by Django 6.0.7 on 2026-08-02 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articlepage_body"),
        ("journals", "0012_publicationissue_journals_current_issue_is_published"),
        ("placements", "0009_home_visual_stories_and_placement_alt"),
        ("static_publish", "0005_automatic_placement_publish"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(editable=False, max_length=48, unique=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("single", "Single placement"),
                            ("journal_curation", "Journal curation"),
                            ("bulk_create", "Bulk create"),
                            ("bulk_maintenance", "Bulk maintenance"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("deactivate", "Deactivate"),
                            ("reactivate", "Reactivate"),
                            ("update_schedule", "Update schedule"),
                            ("pin", "Pin"),
                            ("unpin", "Unpin"),
                            ("move", "Move"),
                            ("copy", "Copy"),
                            ("cancel_future", "Cancel future"),
                            ("republish", "Republish"),
                            ("export", "Export"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validating", "Validating"),
                            ("ready", "Ready"),
                            ("executing", "Executing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("current_step", models.CharField(default="article", max_length=24)),
                ("strict_mode", models.BooleanField(default=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("main_site", "Main site"),
                            ("section", "Section"),
                            ("journal", "Journal"),
                            ("article", "Article"),
                            ("search", "Search"),
                            ("category", "Category"),
                        ],
                        default="journal",
                        max_length=20,
                    ),
                ),
                ("target_slug", models.SlugField(blank=True, max_length=120)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                (
                    "publish_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("queued", "Queued"),
                            ("pending_approval", "Pending approval"),
                            ("publishing", "Publishing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled back"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_placement_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publish_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placement_batches",
                        to="static_publish.staticpublishjob",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="placements.layoutslot",
                    ),
                ),
                (
                    "target_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement_batches",
                        to="journals.journalcategory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_placement_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="PlacementBatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("before_snapshot", models.JSONField(blank=True, default=dict)),
                ("after_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placement_batch_items",
                        to="articles.articlepage",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="placements.placementbatch",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_items",
                        to="placements.articleplacement",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order", "pk"),
            },
        ),
        migrations.CreateModel(
            name="JournalUserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="journals.journal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_favorite"],
                        name="placement_pref_favorite_idx",
                    ),
                    models.Index(
                        fields=["user", "last_used_at"],
                        name="placement_pref_recent_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "journal"), name="placement_user_journal_pref"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="placementbatch",
            index=models.Index(
                fields=["status", "updated_at"], name="placement_batch_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placementbatch",
            index=models.Index(
                fields=["created_by", "updated_at"], name="placement_batch_actor_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="placementbatchitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("article__isnull", False)),
                fields=("batch", "article"),
                name="placement_batch_unique_article",
            ),
        ),
        migrations.AddConstraint(
            model_name="placementbatchitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("placement__isnull", False)),
                fields=("batch", "placement"),
                name="placement_batch_unique_placement",
            ),
        ),
    ]
