# Generated by Django 5.1.15 on 2026-07-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from ai_author_forum.journals.models import import_upload_to


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_cn", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("az_group", models.CharField(max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                ("homepage_intro", models.TextField(blank=True)),
                (
                    "static_site_path",
                    models.CharField(
                        blank=True,
                        help_text="Static homepage path for this journal. Defaults to /journals/{slug}/index.html.",
                        max_length=255,
                    ),
                ),
                ("target_article_count", models.PositiveSmallIntegerField(default=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "metrics_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "journal",
                "verbose_name_plural": "journals",
            },
        ),
        migrations.CreateModel(
            name="JournalImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file", models.FileField(upload_to=import_upload_to)),
                ("package_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("ready", "Ready"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                (
                    "error_report",
                    models.FileField(blank=True, upload_to=import_upload_to),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "journal import job",
                "verbose_name_plural": "journal import jobs",
            },
        ),
        migrations.CreateModel(
            name="ArticleImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_file", models.FileField(upload_to=import_upload_to)),
                ("package_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("ready", "Ready"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                (
                    "error_report",
                    models.FileField(blank=True, upload_to=import_upload_to),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "article import job",
                "verbose_name_plural": "article import jobs",
            },
        ),
        migrations.CreateModel(
            name="StaticArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("ai_article", "AI Article"),
                            ("news", "News"),
                            ("opinion", "Opinion"),
                            ("review", "Review"),
                            ("editorial", "Editorial"),
                        ],
                        default="ai_article",
                        max_length=20,
                    ),
                ),
                ("authors", models.TextField(blank=True)),
                ("ai_co_authors", models.TextField(blank=True)),
                ("abstract", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                (
                    "html_source",
                    models.FileField(blank=True, upload_to="journal-articles/html/"),
                ),
                ("source_html_path", models.CharField(blank=True, max_length=255)),
                ("static_output_path", models.CharField(blank=True, max_length=255)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("placed", "Placed"),
                            ("built", "Built"),
                            ("published", "Published"),
                            ("offline", "Offline"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("build_version", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="journals.journal",
                    ),
                ),
            ],
            options={
                "ordering": ["journal__sort_order", "sort_order", "title"],
                "verbose_name": "static article",
                "verbose_name_plural": "static articles",
            },
        ),
        migrations.CreateModel(
            name="ArticlePlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_code", models.CharField(db_index=True, max_length=80)),
                ("slot_name", models.CharField(blank=True, max_length=255)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("main", "Main site"),
                            ("journal", "Journal site"),
                            ("section", "Section"),
                            ("search", "Search"),
                        ],
                        default="main",
                        max_length=20,
                    ),
                ),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("list", "List"),
                            ("grid", "Grid"),
                            ("rail", "Rail"),
                        ],
                        default="list",
                        max_length=20,
                    ),
                ),
                (
                    "source_mode",
                    models.CharField(
                        choices=[("manual", "Manual"), ("auto", "Automatic")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("pinned", models.BooleanField(default=False)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("display_title", models.CharField(blank=True, max_length=255)),
                ("display_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="journals.staticarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="JournalAssetBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("cover", "Cover"),
                            ("metrics", "Metrics"),
                            ("article", "Article"),
                            ("hero", "Hero"),
                        ],
                        max_length=20,
                    ),
                ),
                ("used_by", models.CharField(blank=True, max_length=255)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("bound", "Bound"),
                            ("pending", "Pending"),
                            ("missing", "Missing"),
                        ],
                        default="bound",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_bindings",
                        to="journals.journal",
                    ),
                ),
            ],
            options={
                "ordering": ["journal__sort_order", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="JournalImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_no", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("updated", "Updated"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("action", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="journals.journal",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="journals.journalimportjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_no", "id"],
                "verbose_name": "journal import row",
                "verbose_name_plural": "journal import rows",
            },
        ),
        migrations.CreateModel(
            name="ArticleImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_no", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("updated", "Updated"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("action", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="journals.staticarticle",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="journals.articleimportjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_no", "id"],
                "verbose_name": "article import row",
                "verbose_name_plural": "article import rows",
            },
        ),
        migrations.AddConstraint(
            model_name="staticarticle",
            constraint=models.UniqueConstraint(
                fields=("journal", "slug"),
                name="journals_staticarticle_journal_slug_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleplacement",
            constraint=models.UniqueConstraint(
                fields=("article", "slot_code"),
                name="journals_articleplacement_article_slot_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalassetbinding",
            constraint=models.UniqueConstraint(
                fields=("journal", "asset_type", "source_name"),
                name="journals_assetbinding_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalimportrow",
            constraint=models.UniqueConstraint(
                fields=("job", "row_no"), name="journals_journalimportrow_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="articleimportrow",
            constraint=models.UniqueConstraint(
                fields=("job", "row_no"), name="journals_articleimportrow_unique"
            ),
        ),
    ]
