# Generated by Django 6.0.7 on 2026-07-19 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddConstraint(
            model_name="journal",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="journals_journal_slug_unique"
            ),
        ),
    ]
