# Generated by Django 6.0.7 on 2026-07-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("journals", "0003_normalize_article_static_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="metrics_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="images.customimage",
            ),
        ),
    ]
