# Generated by Django 6.0.7 on 2026-07-21 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("journals", "0004_alter_journal_cover_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=64)),
                ("slug", models.SlugField(max_length=120)),
                ("depth", models.PositiveSmallIntegerField(default=1, editable=False)),
                ("path_cache", models.CharField(editable=False, max_length=380)),
                ("description", models.TextField(blank=True)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("search_description", models.CharField(blank=True, max_length=500)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("hidden", "Hidden"),
                            ("disabled", "Disabled"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("show_in_navigation", models.BooleanField(default=False)),
                ("generate_static_page", models.BooleanField(default=True)),
                ("aggregate_descendants", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="images.customimage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_journal_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="journals.journal",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="journals.journalcategory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_journal_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "journal category",
                "verbose_name_plural": "journal categories",
                "ordering": ["journal_id", "parent_id", "sort_order", "name", "pk"],
                "permissions": [
                    ("move_journalcategory", "Can move journal categories"),
                    ("change_category_status", "Can change journal category status"),
                    ("archive_journalcategory", "Can archive journal categories"),
                    ("migrate_category_references", "Can migrate category references"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalCategoryPathRedirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_path", models.CharField(max_length=500)),
                ("new_path", models.CharField(max_length=500)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("move", "Move"),
                            ("slug_change", "Slug change"),
                            ("manual_migration", "Manual migration"),
                        ],
                        default="move",
                        max_length=24,
                    ),
                ),
                ("http_status", models.PositiveSmallIntegerField(default=301)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="path_redirects",
                        to="journals.journalcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_category_redirects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_path_redirects",
                        to="journals.journal",
                    ),
                ),
            ],
            options={
                "ordering": ["journal_id", "old_path", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaticArticleCategoryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_assignments",
                        to="journals.staticarticle",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="static_article_assignments",
                        to="journals.journalcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="journalcategory",
            index=models.Index(
                fields=["journal", "status", "sort_order"],
                name="journals_jo_journal_d47316_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalcategory",
            index=models.Index(
                fields=["journal", "parent", "sort_order"],
                name="journals_jo_journal_129727_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalcategory",
            index=models.Index(
                fields=["journal", "path_cache"], name="journals_jo_journal_749f11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalcategory",
            index=models.Index(
                fields=["status", "show_in_navigation"],
                name="journals_jo_status_fcd7ab_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalcategory",
            constraint=models.UniqueConstraint(
                fields=("journal", "code"), name="uniq_category_code_per_journal"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("journal", "parent", "slug"),
                name="uniq_category_child_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("journal", "slug"),
                name="uniq_category_root_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalcategory",
            constraint=models.UniqueConstraint(
                fields=("journal", "path_cache"), name="uniq_category_path_per_journal"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("depth__gte", 1), ("depth__lte", 3)),
                name="category_depth_between_1_and_3",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalcategorypathredirect",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("journal", "old_path"),
                name="uniq_active_category_old_path",
            ),
        ),
        migrations.AddConstraint(
            model_name="staticarticlecategoryassignment",
            constraint=models.UniqueConstraint(
                fields=("article", "category"),
                name="uniq_static_article_category_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="staticarticlecategoryassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("article",),
                name="uniq_static_primary_category_per_article",
            ),
        ),
    ]
