# Generated by Django 6.0.7 on 2026-07-22 08:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import ai_author_forum.journals.validators


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("journals", "0005_journalcategory_journalcategorypathredirect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="hero_image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="journal",
            name="hero_kicker",
            field=models.CharField(default="期刊主页", max_length=80),
        ),
        migrations.AddField(
            model_name="journal",
            name="hero_primary_cta_text",
            field=models.CharField(
                blank=True, default="探索人工智能文章", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="hero_primary_cta_url",
            field=models.CharField(
                blank=True,
                default="/explore-content/ai-article/",
                max_length=500,
                validators=[ai_author_forum.journals.validators.validate_public_link],
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="hero_quick_links",
            field=wagtail.fields.StreamField(
                [("link", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "显示文字", "max_length": 60},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "label": "链接地址",
                            "max_length": 500,
                            "validators": [
                                ai_author_forum.journals.validators.validate_public_link
                            ],
                        },
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "在新窗口打开", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("url", 1), ("open_in_new_tab", 2)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="homepage_intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                validators=[
                    ai_author_forum.journals.validators.validate_controlled_rich_text
                ],
            ),
        ),
    ]
