# Generated by Django 6.0.7 on 2026-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0006_journal_hero_image_journal_hero_image_alt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticarticle",
            name="html_source",
            field=models.FileField(
                blank=True, max_length=255, upload_to="journal-articles/html/"
            ),
        ),
    ]
