# Generated by Django 6.0.7 on 2026-07-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articlepage_body"),
        ("journals", "0007_alter_staticarticle_html_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articleimportjob",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articleimportjob",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_article_import_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="articleimportjob",
            name="import_scope",
            field=models.CharField(
                choices=[("global", "Global"), ("journal", "Journal")],
                db_index=True,
                default="global",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="articleimportjob",
            name="source_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="articleimportjob",
            name="target_journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_import_jobs",
                to="journals.journal",
            ),
        ),
        migrations.AddField(
            model_name="articleimportjob",
            name="template_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="articleimportrow",
            name="article_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_rows",
                to="articles.articlepage",
            ),
        ),
        migrations.AddField(
            model_name="articleimportrow",
            name="error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="articleimportrow",
            name="error_field",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="articleimportrow",
            name="normalized_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
