# Generated by Django 6.0.7 on 2026-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0008_articleimportjob_confirmed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleimportjob",
            name="parser_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="articleimportjob",
            name="source_format",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name="articleimportrow",
            name="conversion_warnings",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="articleimportrow",
            name="source_format",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="articleimportrow",
            name="source_path",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
