# Generated by Django 6.0.7 on 2026-07-31 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articlepage_body"),
        ("images", "0001_initial"),
        ("journals", "0010_seed_default_main_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("main_site", "Main site"), ("journal", "Journal")],
                        default="main_site",
                        max_length=20,
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                ("volume_label", models.CharField(blank=True, max_length=64)),
                ("issue_number", models.CharField(blank=True, max_length=64)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("publication_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_issues",
                        to="images.customimage",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_issues",
                        to="journals.journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "publication issue",
                "verbose_name_plural": "publication issues",
                "ordering": ["-publication_date", "-pk"],
                "permissions": [
                    ("publish_publication_issue", "Can publish publication issues"),
                    (
                        "set_current_publication_issue",
                        "Can set the current publication issue",
                    ),
                    ("rollback_publication_issue", "Can roll back publication issues"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IssueArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_label", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_assignments",
                        to="articles.articlepage",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_articles",
                        to="journals.publicationissue",
                    ),
                ),
            ],
            options={
                "verbose_name": "issue article",
                "verbose_name_plural": "issue articles",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="publicationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("journal__isnull", True), ("scope", "main_site")),
                    models.Q(("journal__isnull", False), ("scope", "journal")),
                    _connector="OR",
                ),
                name="journals_issue_scope_matches_journal",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "main_site")),
                fields=("slug",),
                name="journals_main_issue_slug_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "journal")),
                fields=("journal", "slug"),
                name="journals_journal_issue_slug_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True), ("scope", "main_site")),
                fields=("scope",),
                name="journals_one_current_main_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True), ("scope", "journal")),
                fields=("journal",),
                name="journals_one_current_journal_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuearticle",
            constraint=models.UniqueConstraint(
                fields=("issue", "article"), name="journals_issue_article_unique"
            ),
        ),
    ]
