# Generated by Django 6.0.7 on 2026-07-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("journals", "0011_publicationissue_issuearticle_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="publicationissue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_current", False), ("status", "published"), _connector="OR"
                ),
                name="journals_current_issue_is_published",
            ),
        ),
    ]
