# Generated by Django 6.0.7 on 2026-08-04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def seed_editorial_roles(apps, schema_editor):
    EditorialRole = apps.get_model("journals", "EditorialRole")
    for name, name_cn, sort_order in (
        ("Editor-in-Chief", "主编", 10),
        ("Executive Editor", "执行主编", 20),
        ("Associate Editor", "副主编", 30),
    ):
        EditorialRole.objects.get_or_create(
            name=name,
            defaults={"name_cn": name_cn, "sort_order": sort_order},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0012_publicationissue_journals_current_issue_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorialRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("name_cn", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "editorial role",
                "verbose_name_plural": "editorial roles",
                "ordering": ["sort_order", "name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="JournalEditorialMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("affiliation", models.CharField(blank=True, max_length=500)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "journal",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editorial_members",
                        to="journals.journal",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_memberships",
                        to="journals.editorialrole",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal editorial team member",
                "verbose_name_plural": "journal editorial team members",
                "ordering": ["role__sort_order", "role__name", "sort_order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="journaleditorialmember",
            constraint=models.UniqueConstraint(
                fields=("journal", "role", "name"),
                name="journals_unique_editorial_member",
            ),
        ),
        migrations.RunPython(seed_editorial_roles, migrations.RunPython.noop),
    ]
