# Generated by Django 6.0.7 on 2026-08-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0013_editorial_roles_and_journal_team"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JournalEditorialMember",
        ),
        migrations.DeleteModel(
            name="EditorialRole",
        ),
    ]
