# Generated by Django 6.0.7 on 2026-08-04 08:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0014_remove_misplaced_journal_editorial_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="editorial_team_heading",
            field=models.CharField(default="编辑团队", max_length=80),
        ),
        migrations.AddField(
            model_name="journal",
            name="show_editorial_team_on_article_pages",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="JournalEditorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chief_editor", "主编辑"),
                            ("executive_editor", "常务副编辑"),
                            ("associate_editor", "副编辑"),
                        ],
                        max_length=24,
                    ),
                ),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("public_name", models.CharField(max_length=255)),
                ("public_affiliation", models.CharField(blank=True, max_length=500)),
                ("public_role_label", models.CharField(max_length=40)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("show_publicly", models.BooleanField(default=True)),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("end_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_journal_editor_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ended_journal_editor_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editor_assignments",
                        to="journals.journal",
                    ),
                ),
                (
                    "replaced_by_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_assignments",
                        to="journals.journaleditorassignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_editor_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["journal_id", "role", "display_order", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_active", True), ("role", "chief_editor")
                        ),
                        fields=("journal",),
                        name="journals_one_active_chief_editor",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_active", True), ("role", "executive_editor")
                        ),
                        fields=("journal",),
                        name="journals_one_active_executive_editor",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("user", "journal", "role"),
                        name="journals_unique_active_editor_role",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("starts_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="journals_editor_assignment_dates_valid",
                    ),
                ],
            },
        ),
    ]
