# Generated by Django 6.0.8 on 2026-08-06 08:53

from django.db import migrations, models

import ai_author_forum.journals.validators


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0015_journal_editorial_team_heading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="accepts_author_submissions",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="仅控制作者投稿入口；期刊状态、关闭时间和有效主编辑仍会再次校验。",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="submission_closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journal",
            name="submission_guidelines_url",
            field=models.CharField(
                blank=True,
                max_length=500,
                validators=[ai_author_forum.journals.validators.validate_public_link],
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="submission_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
