# Generated by Django 6.0.7 on 2026-07-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("static_publish", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpublishtarget",
            name="action",
            field=models.CharField(
                choices=[
                    ("upsert", "Create or update"),
                    ("redirect", "Redirect"),
                    ("delete", "Delete"),
                ],
                default="upsert",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="canonical_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="dependencies",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="error_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="http_status",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="redirect_to",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="target_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="target_type",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
