# Generated by Django 6.0.7 on 2026-07-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("static_publish", "0002_staticpublishtarget_action_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staticpublishjob",
            options={
                "ordering": ("-created_at",),
                "permissions": (
                    ("publish_static_site", "Can publish static site"),
                    ("publish_category_pages", "Can publish category pages"),
                    ("retry_category_publish", "Can retry category publishing"),
                    ("rollback_category_publish", "Can roll back category publishing"),
                ),
            },
        ),
    ]
