# Generated by Django 6.0.7 on 2026-07-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("static_publish", "0003_alter_staticpublishjob_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpublishjob",
            name="rollback_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="staticpublishtarget",
            name="error_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("template", "模板渲染"),
                    ("data", "数据缺失"),
                    ("asset", "素材缺失"),
                    ("file_write", "文件写入"),
                    ("validation", "校验失败"),
                    ("activation", "切流失败"),
                    ("unknown", "未知错误"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="staticpublishjob",
            name="scope",
            field=models.CharField(
                choices=[
                    ("full", "全站发布"),
                    ("selective", "指定路径"),
                    ("retry", "失败目标重试"),
                    ("rollback", "版本回滚"),
                ],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staticpublishjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "生成中"),
                    ("succeeded", "已成功并切换"),
                    ("partial", "部分失败"),
                    ("failed", "失败"),
                    ("rolled_back", "已回滚"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staticpublishtarget",
            name="action",
            field=models.CharField(
                choices=[
                    ("upsert", "创建或更新"),
                    ("redirect", "重定向"),
                    ("delete", "删除"),
                ],
                default="upsert",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="staticpublishtarget",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "生成中"),
                    ("succeeded", "成功"),
                    ("failed", "失败"),
                    ("skipped", "已跳过"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="staticpublishtarget",
            index=models.Index(
                fields=["job", "status"], name="sp_target_job_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staticpublishtarget",
            index=models.Index(
                fields=["job", "target_type"], name="sp_target_job_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staticpublishtarget",
            index=models.Index(
                fields=["job", "error_category"], name="sp_target_job_error_idx"
            ),
        ),
    ]
