# Generated by Django 6.0.7 on 2026-07-30 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("static_publish", "0004_staticpublishjob_rollback_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staticpublishjob",
            name="coalesce_key",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="staticpublishjob",
            name="is_automatic",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="staticpublishjob",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="staticpublishjob",
            index=models.Index(
                fields=["is_automatic", "status", "scheduled_at"],
                name="sp_job_auto_schedule_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="staticpublishjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_automatic", True), ("status", "pending")),
                fields=("coalesce_key",),
                name="sp_one_pending_auto_coalesce_key",
            ),
        ),
    ]
