# Generated by Django 6.0.7 on 2026-07-31 08:19

import wagtail.fields
from django.db import migrations

import ai_author_forum.journals.validators


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="footer_navigation",
            field=wagtail.fields.StreamField(
                [("link_section", 7)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.PageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Leave blank to use page's listing title.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 1), ("title", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "validators": [
                                ai_author_forum.journals.validators.validate_public_link
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("link", 4), ("title", 0)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [[("internal", 3), ("external", 5)]],
                        {"label": "Links", "max_num": None},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("section_heading", 0), ("links", 6)]],
                        {},
                    ),
                },
            ),
        ),
    ]
