# Generated by Django 6.0.7 on 2026-07-19 10:55

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("journals", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="articles_articlepage",
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("abstract", models.TextField()),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("image", 3), ("quote", 5), ("list", 9)],
                        block_lookup={
                            0: (
                                "ai_author_forum.articles.blocks.ParagraphBlock",
                                (),
                                {},
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("caption", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.TextBlock", (), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 4), ("attribution", 2)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("unordered", "Unordered"),
                                        ("ordered", "Ordered"),
                                    ]
                                },
                            ),
                            7: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link"]},
                            ),
                            8: ("wagtail.blocks.ListBlock", (7,), {"min_num": 1}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("list_type", 6), ("items", 8)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "authors",
                    models.CharField(
                        help_text="Comma-separated author names.", max_length=255
                    ),
                ),
                ("ai_co_authors", models.CharField(blank=True, max_length=255)),
                ("ai_contribution_statement", models.TextField(blank=True)),
                ("responsibility_statement", models.TextField(blank=True)),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("AI Article", "AI Article"),
                            ("News", "News"),
                            ("Opinion", "Opinion"),
                            ("Research Analysis", "Research Analysis"),
                        ],
                        default="AI Article",
                        max_length=32,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        help_text="Comma-separated keywords.", max_length=255
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "static_slug",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Static HTML output path segment. Leave blank to generate from the title.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "approved_version",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Revision approved during article moderation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                    ),
                ),
                (
                    "primary_journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_articles",
                        to="journals.journal",
                    ),
                ),
                (
                    "rejected_version",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Revision rejected during article moderation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                    ),
                ),
                (
                    "related_journals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_articles",
                        to="journals.journal",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("edit_article", "Can edit articles"),
                    ("review_article", "Can review articles"),
                    ("trigger_article_placement", "Can trigger article placement"),
                ],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ArticleReviewRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_records",
                        to="articles.articlepage",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="article_review_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleReviewTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.task",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        help_text="Pages/snippets at this step in a workflow will be moderated or approved by these groups of users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article review task",
                "verbose_name_plural": "Article review tasks",
            },
            bases=("wagtailcore.task",),
        ),
    ]
