# Generated by Django 6.0.7 on 2026-07-19 12:12


import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


def _read_source(static_article):
    if not static_article.html_source:
        return ""
    try:
        with static_article.html_source.open("rb") as handle:
            return handle.read().decode("utf-8")
    except (OSError, ValueError):
        return ""


def _unique_slug(ArticlePage, base_slug, journal_slug):
    base_slug = (base_slug or "article")[:255]
    if not ArticlePage.objects.filter(static_slug=base_slug).exists():
        return base_slug
    candidate = f"{journal_slug}-{base_slug}"[:255]
    suffix = 2
    while ArticlePage.objects.filter(static_slug=candidate).exists():
        suffix_text = f"-{suffix}"
        candidate = (
            f"{journal_slug}-{base_slug}"[: 255 - len(suffix_text)] + suffix_text
        )
        suffix += 1
    return candidate


def _unique_page_slug(ArticlePage, base_slug, journal_slug):
    base_slug = (base_slug or "article")[:255]
    if not ArticlePage.objects.filter(slug=base_slug).exists():
        return base_slug
    candidate = f"{journal_slug}-{base_slug}"[:255]
    suffix = 2
    while ArticlePage.objects.filter(slug=candidate).exists():
        suffix_text = f"-{suffix}"
        candidate = (
            f"{journal_slug}-{base_slug}"[: 255 - len(suffix_text)] + suffix_text
        )
        suffix += 1
    return candidate


def migrate_static_articles(apps, schema_editor):
    StaticArticle = apps.get_model("journals", "StaticArticle")
    ArticlePage = apps.get_model("articles", "ArticlePage")
    Page = apps.get_model("wagtailcore", "Page")
    root = Page.objects.order_by("path", "pk").first()
    if root is None:
        return

    type_map = {
        "ai_article": "AI Article",
        "news": "News",
        "opinion": "Opinion",
        "review": "Research Analysis",
        "editorial": "Research Analysis",
    }
    status_map = {
        "draft": "draft",
        "review": "submitted",
        "approved": "approved",
        "placed": "approved",
        "built": "approved",
        "published": "published",
        "offline": "rejected",
    }
    for legacy in StaticArticle.objects.select_related("journal").all().iterator():
        if ArticlePage.objects.filter(source_static_article_id=legacy.pk).exists():
            continue
        static_slug = _unique_slug(ArticlePage, legacy.slug, legacy.journal.slug)
        page_slug = _unique_page_slug(ArticlePage, legacy.slug, legacy.journal.slug)
        body_source = _read_source(legacy)
        body = (
            [("html", body_source)]
            if body_source
            else [("paragraph", f"<p>{legacy.abstract or legacy.title}</p>")]
        )
        page = ArticlePage(
            title=legacy.title,
            slug=page_slug,
            abstract=legacy.abstract or legacy.title,
            body=body,
            authors=legacy.authors or "Imported author",
            ai_co_authors=legacy.ai_co_authors,
            article_type=type_map.get(legacy.article_type, "AI Article"),
            primary_journal_id=legacy.journal_id,
            keywords=legacy.keywords,
            review_status=status_map.get(legacy.review_status, "draft"),
            static_slug=static_slug,
            source_static_article_id=legacy.pk,
        )
        root.add_child(instance=page)
        if page.review_status == "published":
            page.live = True
            page.save(update_fields=("live",))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("journals", "0002_alter_journal_sort_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="source_static_article",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="canonical_page",
                to="journals.staticarticle",
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("paragraph", 1),
                    ("image", 4),
                    ("quote", 6),
                    ("list", 10),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("ai_author_forum.articles.blocks.ParagraphBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.TextBlock", (), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 5), ("attribution", 3)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("unordered", "Unordered"),
                                ("ordered", "Ordered"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {"min_num": 1}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 7), ("items", 9)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.RunPython(migrate_static_articles, noop),
    ]
