# Generated by Django 6.0.7 on 2026-07-19 18:00

from django.db import migrations, models


def migrate_publication_status(apps, schema_editor):
    ArticlePage = apps.get_model("articles", "ArticlePage")
    StaticArticle = apps.get_model("journals", "StaticArticle")
    legacy_by_id = {
        article.pk: article
        for article in StaticArticle.objects.only(
            "pk", "review_status", "build_version"
        ).iterator()
    }
    publication_statuses = {"approved", "placed", "built", "published", "offline"}

    for article in ArticlePage.objects.all().iterator():
        legacy = legacy_by_id.get(article.source_static_article_id)
        if legacy is not None:
            legacy_status = legacy.review_status
            article.publication_status = (
                legacy_status if legacy_status in publication_statuses else ""
            )
            article.build_version = legacy.build_version
            article.published_version = (
                legacy.build_version if legacy_status == "published" else ""
            )
            if legacy_status in publication_statuses:
                article.review_status = "approved"
        elif article.review_status == "published":
            article.review_status = "approved"
            article.publication_status = "approved"
        elif article.review_status == "approved":
            article.publication_status = "approved"

        article.save(
            update_fields=(
                "review_status",
                "publication_status",
                "build_version",
                "published_version",
            )
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_unify_imported_articles"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="build_version",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Most recent static release version where this article rendered successfully.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="last_built_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="last_static_published_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "Approved for placement"),
                    ("placed", "Placed"),
                    ("built", "Static HTML built"),
                    ("published", "Published"),
                    ("offline", "Offline"),
                ],
                db_index=True,
                default="",
                editable=False,
                help_text="Static delivery state. Review approval and frontend publication are tracked separately.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="publish_failure_reason",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="published_version",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Active static release version currently containing this article.",
                max_length=64,
            ),
        ),
        migrations.RunPython(migrate_publication_status, noop),
    ]
