# Generated by Django 6.0.7 on 2026-07-21 04:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_publication_status_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategoryAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "article",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_assignments",
                        to="articles.articlepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "permissions": [
                    ("assign_articlecategory", "Can assign article categories")
                ],
                "abstract": False,
            },
        ),
    ]
