# Generated by Django 6.0.7 on 2026-07-21 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_articlecategoryassignment"),
        ("journals", "0005_journalcategory_journalcategorypathredirect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecategoryassignment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_assignments",
                to="journals.journalcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="articlecategoryassignment",
            constraint=models.UniqueConstraint(
                fields=("article", "category"), name="uniq_article_category_assignment"
            ),
        ),
        migrations.AddConstraint(
            model_name="articlecategoryassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("article",),
                name="uniq_primary_category_per_article",
            ),
        ),
    ]
