# Generated by Django 6.0.7 on 2026-07-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_articlecategoryassignment_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="placement_sync_error",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="placement_sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                ],
                default="pending",
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="placement_synced_revision_id",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
