# Generated by Django 6.0.7 on 2026-07-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_repair_article_approval_and_sync_state"),
        ("images", "0001_initial"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlecategoryassignment",
            options={
                "ordering": ["sort_order"],
                "permissions": [("assign_articlecategory", "可分配文章动态栏目")],
            },
        ),
        migrations.AlterModelOptions(
            name="articlepage",
            options={
                "permissions": [
                    ("edit_article", "可编辑文章"),
                    ("review_article", "可审核文章"),
                    ("trigger_article_placement", "可管理文章投放"),
                    ("use_raw_html", "可使用文章 Raw HTML 正文块"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="articlereviewtask",
            options={
                "verbose_name": "文章审核任务",
                "verbose_name_plural": "文章审核任务",
            },
        ),
        migrations.AddField(
            model_name="articlepage",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="images.customimage",
                verbose_name="文章封面",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="featured_image_alt",
            field=models.CharField(
                blank=True,
                help_text="用于无障碍访问；留空时依次使用图片标题和文章标题。",
                max_length=255,
                verbose_name="封面替代文本",
            ),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                help_text="本次审核操作明确针对的文章 revision。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_review_records",
                to="wagtailcore.revision",
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="approved_version",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="文章审核通过时对应的 revision。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="article_type",
            field=models.CharField(
                choices=[
                    ("AI Article", "AI 文章"),
                    ("News", "新闻"),
                    ("Opinion", "观点"),
                    ("Research Analysis", "研究分析"),
                ],
                default="AI Article",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="authors",
            field=models.CharField(
                help_text="多个作者请使用英文逗号分隔。", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="build_version",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="最近一次成功生成该文章的静态发布版本。",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="keywords",
            field=models.CharField(
                help_text="多个关键词请使用英文逗号分隔。", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="placement_sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "待同步"),
                    ("synced", "已同步"),
                    ("failed", "同步失败"),
                ],
                default="pending",
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="publication_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "已通过，待投放"),
                    ("placed", "已投放"),
                    ("built", "静态 HTML 已构建"),
                    ("published", "静态版本已发布"),
                    ("offline", "已下线"),
                ],
                db_index=True,
                default="",
                editable=False,
                help_text="静态交付状态；文章审核通过与前台发布分别记录。",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="published_version",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="当前包含该文章的活动静态发布版本。",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="rejected_version",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="文章审核驳回时对应的 revision。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待审核"),
                    ("approved", "审核通过"),
                    ("rejected", "已驳回"),
                    ("published", "已发布（兼容状态）"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="static_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="静态 HTML 输出路径片段；留空时根据文章标题自动生成。",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="articlereviewrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("submitted", "已提交审核"),
                    ("approved", "审核通过"),
                    ("rejected", "已驳回"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="articlereviewrecord",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
