# Generated by Django 6.0.7 on 2026-07-25 15:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_alter_articlecategoryassignment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("heading", 1),
                    ("image", 5),
                    ("quote", 8),
                    ("list", 12),
                    ("table", 13),
                    ("document", 17),
                    ("html", 18),
                ],
                block_lookup={
                    0: ("ai_author_forum.articles.blocks.ParagraphBlock", (), {}),
                    1: ("ai_author_forum.articles.blocks.HeadingBlock", (), {}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "图片"},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "用于无障碍访问；留空时使用图片库标题。",
                            "label": "替代文本",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "图片说明", "max_length": 255, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("alt_text", 3), ("caption", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.TextBlock", (), {"label": "引用内容"}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "出处 / 作者", "max_length": 255, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 6), ("attribution", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("unordered", "无序列表"),
                                ("ordered", "有序列表"),
                            ],
                            "label": "列表类型",
                        },
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"]},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {"label": "列表项", "min_num": 1},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("list_type", 9), ("items", 11)]],
                        {},
                    ),
                    13: ("ai_author_forum.articles.blocks.ArticleTableBlock", (), {}),
                    14: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"label": "文档"},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "留空时使用文档标题。",
                            "label": "链接文字",
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "说明", "max_length": 500, "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("document", 14), ("link_text", 15), ("description", 16)]],
                        {},
                    ),
                    18: (
                        "ai_author_forum.articles.blocks.AdvancedRawHTMLBlock",
                        (),
                        {},
                    ),
                },
                help_text="默认使用可视化正文段落，也可按需插入章节标题、图片、引用、列表、表格和附件；无需手写 HTML。",
                verbose_name="正文",
            ),
        ),
    ]
