# Generated by Django 6.0.7 on 2026-08-04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def create_contributors_from_legacy_authors(apps, schema_editor):
    ArticlePage = apps.get_model("articles", "ArticlePage")
    ArticleContributor = apps.get_model("articles", "ArticleContributor")

    for article in ArticlePage.objects.exclude(authors="").iterator():
        names = [name.strip() for name in article.authors.split(",") if name.strip()]
        for position, name in enumerate(names):
            ArticleContributor.objects.create(
                article_id=article.pk,
                identity="author",
                name=name,
                sort_order=position,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_articlepage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleContributor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "identity",
                    models.CharField(
                        choices=[
                            ("author", "作者"),
                            ("editor_in_chief", "主编"),
                            ("executive_editor", "执行主编"),
                            ("associate_editor", "副编辑"),
                            ("custom", "自定义身份"),
                        ],
                        default="author",
                        max_length=32,
                        verbose_name="身份",
                    ),
                ),
                (
                    "custom_identity",
                    models.CharField(
                        blank=True,
                        help_text="仅在身份选择“自定义身份”时填写。",
                        max_length=120,
                        verbose_name="自定义身份",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="姓名")),
                (
                    "affiliation",
                    models.CharField(blank=True, max_length=500, verbose_name="单位"),
                ),
                (
                    "is_corresponding",
                    models.BooleanField(default=False, verbose_name="通讯作者"),
                ),
                (
                    "article",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="articles.articlepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章作者或编辑",
                "verbose_name_plural": "文章作者或编辑",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="authors",
            field=models.CharField(
                blank=True,
                help_text="多个作者请使用英文逗号分隔。",
                max_length=255,
            ),
        ),
        migrations.RunPython(
            create_contributors_from_legacy_authors,
            migrations.RunPython.noop,
        ),
    ]
