# Generated by Django 6.0.7 on 2026-08-04 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def map_legacy_submissions(apps, schema_editor):
    ArticleReviewRecord = apps.get_model("articles", "ArticleReviewRecord")
    ArticleReviewRecord.objects.filter(action="submitted").update(
        stage="initial",
        action="submit",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_articlecontributor_and_legacy_authors"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("journals", "0015_journal_editorial_team_heading_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="assigned_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_initial_review_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="assigned_initial_editor",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_initial_review_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="assignment_request_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="journal_editor_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_review_records",
                to="journals.journaleditorassignment",
            ),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="request_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="reviewer_role",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[("initial", "初审"), ("final", "终审")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("submitted", "待初审"),
                    ("pending_final", "待终审"),
                    ("approved", "审核通过"),
                    ("rejected", "已驳回"),
                    ("published", "已发布（兼容状态）"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="articlereviewrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit", "提交初审"),
                    ("initial_approve", "初审通过"),
                    ("initial_return", "初审退回"),
                    ("initial_reject", "初审拒绝"),
                    ("final_approve", "终审通过"),
                    ("final_return", "终审退回"),
                    ("final_reject", "终审拒绝"),
                    ("reopen", "重新开启"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="articlereviewrecord",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                help_text="本次审核操作明确针对的文章 revision。",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="article_review_records",
                to="wagtailcore.revision",
            ),
        ),
        migrations.RunPython(map_legacy_submissions, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ArticleFinalReviewTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.task",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        help_text="Pages/snippets at this step in a workflow will be moderated or approved by these groups of users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章终审任务",
                "verbose_name_plural": "文章终审任务",
            },
            bases=("wagtailcore.task",),
        ),
        migrations.CreateModel(
            name="ArticleInitialReviewTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.task",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        help_text="Pages/snippets at this step in a workflow will be moderated or approved by these groups of users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章初审任务",
                "verbose_name_plural": "文章初审任务",
            },
            bases=("wagtailcore.task",),
        ),
    ]
