# Generated by Django 6.0.7 on 2026-08-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_articlepage_assigned_at_articlepage_assigned_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="ai_contribution_statement",
            field=models.TextField(blank=True, verbose_name="AI 参与说明"),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="responsibility_statement",
            field=models.TextField(blank=True, verbose_name="作者声明"),
        ),
    ]
