# Generated by Django 6.0.7 on 2026-08-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_alter_articlepage_ai_contribution_statement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlereviewrecord",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_records",
                to="articles.articlepage",
            ),
        ),
    ]
