# Generated by Django 6.0.8 on 2026-08-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_alter_articlereviewrecord_article"),
        ("images", "0001_initial"),
        ("journals", "0016_journal_accepts_author_submissions_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="first_submitted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="has_ever_been_submitted",
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="last_submitted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="author_visible_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="authorship_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="content_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="submission_journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author_submission_review_records",
                to="journals.journal",
            ),
        ),
        migrations.AlterField(
            model_name="articlereviewrecord",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit", "提交初审"),
                    ("initial_approve", "初审通过"),
                    ("initial_return", "初审退回"),
                    ("initial_reject", "初审拒绝"),
                    ("final_approve", "终审通过"),
                    ("final_return", "终审退回"),
                    ("final_reject", "终审拒绝"),
                    ("reopen", "重新开启"),
                    ("transfer", "受控转投"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ArticleAuthorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "投稿负责人"), ("co_author", "共同作者")],
                        max_length=16,
                    ),
                ),
                ("can_edit", models.BooleanField(default=False)),
                ("is_corresponding", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorships",
                        to="articles.articlepage",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_article_authorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="article_authorships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["article_id", "role", "created_at", "pk"],
                "permissions": [("manage_article_authorship", "可管理文章投稿关系")],
            },
        ),
        migrations.AddField(
            model_name="articlereviewrecord",
            name="submission_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submission_review_records",
                to="articles.articleauthorship",
            ),
        ),
        migrations.CreateModel(
            name="AuthorSubmissionAsset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("cover", "文章封面"), ("attachment", "投稿附件")],
                        max_length=16,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "待扫描"),
                            ("clean", "通过"),
                            ("rejected", "已拒绝"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("scan_detail", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_assets",
                        to="articles.articlepage",
                    ),
                ),
                (
                    "authorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="articles.articleauthorship",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_submission_assets",
                        to="images.customimage",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_submission_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["article_id", "kind", "-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="AuthorSubmissionOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建投稿"),
                            ("save", "保存投稿"),
                            ("change_journal", "作者更换期刊"),
                            ("submit", "提交初审"),
                            ("grant", "授予投稿关系"),
                            ("revoke", "撤销投稿关系"),
                            ("transfer", "编辑受控转投"),
                        ],
                        max_length=24,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_submission_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_operations",
                        to="articles.articlepage",
                    ),
                ),
                (
                    "authorship",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="articles.articleauthorship",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author_submission_operations",
                        to="wagtailcore.revision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="articleauthorship",
            index=models.Index(
                fields=["user", "revoked_at", "can_edit"],
                name="articles_ar_user_id_a81ade_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="articleauthorship",
            index=models.Index(
                fields=["article", "revoked_at", "role"],
                name="articles_ar_article_9da65e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleauthorship",
            constraint=models.UniqueConstraint(
                fields=("article", "user"),
                name="articles_unique_article_user_authorship",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleauthorship",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True), ("role", "owner")),
                fields=("article",),
                name="articles_one_effective_submission_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleauthorship",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_corresponding", True), ("revoked_at__isnull", True)
                ),
                fields=("article",),
                name="articles_one_effective_corresponding_author",
            ),
        ),
        migrations.AddConstraint(
            model_name="articleauthorship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("can_edit", False),
                    ("role", "owner"),
                    ("accepted_at__isnull", False),
                    _connector="OR",
                ),
                name="articles_authorship_edit_requires_acceptance",
            ),
        ),
        migrations.AddIndex(
            model_name="authorsubmissionasset",
            index=models.Index(
                fields=["article", "kind", "is_active"],
                name="articles_au_article_b3c1d3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="authorsubmissionasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("image__isnull", False), ("kind", "cover")),
                    ("kind", "attachment"),
                    _connector="OR",
                ),
                name="articles_author_asset_kind_payload",
            ),
        ),
        migrations.AddIndex(
            model_name="authorsubmissionoperation",
            index=models.Index(
                fields=["article", "action", "created_at"],
                name="articles_au_article_5f3ab9_idx",
            ),
        ),
    ]
