# Generated by Django 6.0.8 on 2026-08-07 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0014_articlepage_first_submitted_at_and_more"),
        ("images", "0001_initial"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authorsubmissionasset",
            name="articles_author_asset_kind_payload",
        ),
        migrations.AddField(
            model_name="authorsubmissionasset",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="author_submission_assets",
                to="wagtaildocs.document",
            ),
        ),
        migrations.AlterField(
            model_name="authorsubmissionasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cover", "文章封面"),
                    ("inline_image", "正文图片"),
                    ("attachment", "投稿附件"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="authorsubmissionasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("document__isnull", True),
                        ("image__isnull", False),
                        ("kind__in", ["cover", "inline_image"]),
                    ),
                    models.Q(
                        ("document__isnull", False),
                        ("image__isnull", True),
                        ("kind", "attachment"),
                    ),
                    _connector="OR",
                ),
                name="articles_author_asset_kind_payload",
            ),
        ),
    ]
