import re
from pathlib import Path

T = {
    "新建文章": "Create article",
    "导入本刊文章": "Import journal articles",
    "一键导入文章": "Import articles",
    "文章工作流程": "Article workflow",
    "当前主对象": "Current primary object",
    "文章": "Article",
    "先归属": "Assign first",
    "后审核": "review next",
    "再投放": "then place",
    "文章以主属子期刊归档": "Articles are filed under their primary journal",
    "相关子期刊只表示跨刊内容关系": "Related journals only indicate cross-journal content relationships",
    "审核通过后仍需进入投放管理": "Approved articles must still be configured in Placement management",
    "最后由静态发布生成前台": "Static publishing then generates the public HTML",
    "文章归属": "Article assignment",
    "内容审核": "Content review",
    "版位投放": "Slot placement",
    "静态发布": "Static publishing",
    "当前子期刊上下文": "Current journal context",
    "正在处理子期刊": "Working in journal",
    "下方列表仅显示以本刊为": "The list below only shows articles whose",
    "主属期刊": "primary journal",
    "的文章": "is this journal",
    "不代表这些文章已经投放到本刊前台": "This does not mean they have been placed on this journal's public site",
    "返回子期刊工作台": "Return to journal workspace",
    "管理本刊投放": "Manage journal placements",
    "文章筛选": "Article filters",
    "关键词": "Keyword",
    "标题": "Title",
    "摘要": "Summary",
    "正文": "Body",
    "作者或关键词": "author, or keyword",
    "审核状态": "Review status",
    "全部审核状态": "All review statuses",
    "交付状态": "Delivery status",
    "全部交付状态": "All delivery statuses",
    "文章类型": "Article type",
    "全部类型": "All types",
    "全部期刊": "All journals",
    "动态栏目": "Dynamic category",
    "全部栏目": "All categories",
    "提交人": "Submitter",
    "用户名": "Username",
    "等待时长": "Waiting time",
    "全部": "All",
    "超过": "More than",
    "小时": "hours",
    "天": "days",
    "更新日期起": "Updated from",
    "更新日期止": "Updated to",
    "排序": "Sort",
    "每页": "Per page",
    "条": "items",
    "应用筛选": "Apply filters",
    "清空筛选": "Clear filters",
    "筛选结果": "Filtered results",
    "篇": "articles",
    "第": "Page",
    "页": "page",
    "待审核列表固定审核状态为": "The pending-review list always uses review status",
    "待审核": "Pending review",
    "选择当前页全部文章": "Select all articles on this page",
    "封面和标题": "Cover and title",
    "主属期刊与栏目": "Primary journal and category",
    "类型": "Type",
    "提交信息": "Submission",
    "最近更新": "Last updated",
    "最近编辑人": "Last editor",
    "操作": "Actions",
    "选择": "Select",
    "未分配栏目": "No category assigned",
    "未进入交付": "Not in delivery",
    "等待": "Waiting",
    "未知提交人": "Unknown submitter",
    "编辑": "Edit",
    "提交审核": "Submit for review",
    "分配主栏目": "Assign primary category",
    "进入审核": "Start review",
    "查看审核": "View review",
    "动态预览": "Dynamic preview",
    "静态页面预览": "Static page preview",
    "管理投放": "Manage placements",
    "版本历史": "Revision history",
    "无可用操作": "No available actions",
    "没有符合当前筛选条件的文章": "No articles match the current filters",
    "已选": "selected",
    "导入草稿请先": "For imported drafts, first",
    "设置主栏目": "set the primary category",
    "再": "then",
    "批量操作不会自动审核通过": "Bulk actions do not automatically approve articles",
    "投放或静态发布": "placement or static publishing",
    "批量操作": "Bulk actions",
    "请选择操作": "Choose an action",
    "设置主属期刊": "Set primary journal",
    "增加动态栏目": "Add dynamic category",
    "设置文章类型": "Set article type",
    "批量批准": "Bulk approve",
    "批量驳回": "Bulk reject",
    "目标主属期刊": "Target primary journal",
    "请选择": "Select",
    "目标主栏目": "Target primary category",
    "新增动态栏目": "Additional dynamic category",
    "目标文章类型": "Target article type",
    "审核意见": "Review comment",
    "批量批准或驳回时必填": "Required for bulk approval or rejection",
    "执行批量操作": "Run bulk action",
    "一次最多": "Up to",
    "文章列表不支持批量前台发布": "The article list does not support bulk public publishing",
    "审核通过后仍需投放和静态发布": "Approved articles still require placement and static publishing",
    "批量处理结果": "Bulk action results",
    "复制失败原因": "Copy failure reason",
    "下载失败清单": "Download failure list",
    "结果": "Result",
    "说明": "Details",
    "文章分页": "Article pagination",
    "上一页": "Previous",
    "下一页": "Next",
    "成功": "Succeeded",
    "失败": "Failed",
    "文章批量处理失败清单": "Article bulk-action failure list",
    "批量批准或驳回必须填写审核意见": "A review comment is required for bulk approval or rejection",
    "此操作会逐篇保存业务记录和": "This action saves business records and",
    "确认继续": "Confirm and continue",
    "批量处理请求失败": "Bulk-action request failed",
    "请刷新页面后重试": "Refresh the page and try again",
    "批量处理失败": "Bulk action failed",
    "共选择": "Selected",
    "仅审核通过且已上线的文章可进入投放": "Only approved, live articles can be placed",
    "请先选文章和目标": "Select an article and target first",
    "再配置展示内容与生效时间": "Then configure display content and the active period",
    "审核通过不等于自动上前台": "Approval does not automatically publish to the public site",
    "筛选投放与可用文章": "Filter placements and available articles",
    "先缩小文章": "Narrow the article",
    "目标和版位范围": "target, and slot ranges first",
    "便于快速定位待维护内容": "to quickly locate content that needs maintenance",
    "重置条件": "Reset filters",
    "共有": "There are",
    "篇可投放文章": "placeable articles",
    "目标范围包括主站": "Targets include the main site",
    "固定栏目": "fixed categories",
    "启用中的子期刊和": "active journals, and",
    "静态推荐页": "static recommendations page",
    "批量投放到同一子期刊": "Bulk place into one journal",
    "一次选择多篇审核通过文章": "Select multiple approved articles at once",
    "统一投放到同一个子期刊和固定版位": "Place them into the same journal and fixed slot",
    "批量模式": "Bulk mode",
    "选择子期刊与版位": "Select journal and slot",
    "所选文章将统一进入该目标版位": "Selected articles will all enter this target slot",
    "最大容量": "Maximum capacity",
    "当前占用": "Currently used",
    "剩余容量": "Remaining capacity",
    "批量选择文章": "Select articles in bulk",
    "切换子期刊后": "After switching journals",
    "可用文章列表会自动刷新": "the available article list refreshes automatically",
    "快速筛选": "Quick filter",
    "输入标题或静态": "Enter title or static slug",
    "正在加载该子期刊的可用文章": "Loading available articles for this journal",
    "篇已选择": "articles selected",
    "已启用的重复投放会自动跳过": "Enabled duplicate placements are skipped automatically",
    "统一生效设置": "Shared activation settings",
    "批量设置置顶与生效时间": "Set pinning and activation times in bulk",
    "选择版位后自动检查容量": "Capacity is checked after selecting a slot",
    "一键投放所选文章": "Place selected articles",
    "编辑投放": "Edit placement",
    "受控投放工作台": "Controlled placement workspace",
    "按内容来源": "Configure by content source",
    "投放位置": "placement location",
    "展示覆盖和发布规则四步完成配置": "display overrides, and publishing rules in four steps",
    "右侧会同步显示文章卡片效果": "The article-card preview updates on the right",
    "编辑模式": "Edit mode",
    "新增投放": "Add placement",
    "退出编辑": "Exit editing",
    "改为新增投放": "Switch to new placement",
    "选择文章": "Select article",
    "仅显示当前可投放的正式文章": "Only currently eligible live articles are shown",
    "文章投放条件": "Article placement requirements",
    "审核已通过": "Review approved",
    "文章已上线": "Article is live",
    "期刊已启用": "Journal is active",
    "确定位置": "Choose location",
    "选择页面目标及模板预设版位": "Select a page target and a template-defined slot",
    "区间占用": "Period occupancy",
    "选择目标": "Select target",
    "版位和生效区间后自动检查容量": "Capacity is checked after selecting the slot and active period",
    "设置展示内容": "Configure display content",
    "覆盖项均为可选": "All overrides are optional",
    "留空时沿用文章原始标题": "Leave blank to use the original article title",
    "摘要和图片": "summary, and image",
    "仅影响本次投放卡片": "Only this placement card is affected",
    "不修改文章原标题": "The original article title is not changed",
    "建议控制在": "Recommended limit",
    "行": "lines",
    "便于列表页快速阅读": "for quick reading on list pages",
    "留空时使用文章默认图片": "Leave blank to use the article's default image",
    "安排顺序与时间": "Set order and timing",
    "控制同版位内的优先级以及投放生效区间": "Control priority within the slot and the placement active period",
    "留空表示保存后立即生效": "Leave blank to activate immediately after saving",
    "留空表示长期有效": "Leave blank for no end date",
    "数值越小": "Smaller values",
    "同级排序越靠前": "appear earlier at the same level",
    "优先于同版位普通内容": "Prioritize over regular content in the same slot",
    "关闭后不会进入正式发布": "When disabled, this placement is excluded from publishing",
    "文章卡片预览": "Article card preview",
    "输入内容时实时更新": "Updates as you type",
    "实时": "Live",
    "文章预览图": "Article preview image",
    "选择投放目标": "Select placement target",
    "选择版位": "Select slot",
    "选择文章后显示标题": "Select an article to show its title",
    "摘要覆盖为空时": "When the summary override is blank",
    "正式生成将使用文章原摘要": "publishing uses the original article summary",
    "此处用于快速校对信息层级": "Use this preview to check the information hierarchy",
    "服务端正式组件预览": "The server-rendered component preview",
    "会使用真实模板生成最终效果": "uses the real template for the final result",
    "保存前请确认目标": "Before saving, confirm the target",
    "版位": "Slot",
    "容量和生效时间": "capacity, and active period",
    "正式组件预览": "Server component preview",
    "保存修改": "Save changes",
    "保存投放": "Save placement",
    "正式文章卡片预览": "Server article-card preview",
    "未保存": "not saved",
    "目标": "Target",
    "当前生效内容": "Currently active content",
    "实时投放清单": "Live placement list",
    "排序只作用于同一目标和同一固定版位": "Sorting only applies within the same target and fixed slot",
    "不会改变模板结构": "It does not change the template structure",
    "未来生效内容可通过精确目标和版位筛选维护": "Future content can be maintained using exact target and slot filters",
    "生效区间": "Active period",
    "覆盖": "Overrides",
    "置顶": "Pinned",
    "立即": "Immediately",
    "至": "to",
    "长期": "No end date",
    "图片": "Image",
    "无": "None",
    "上移": "Move up",
    "下移": "Move down",
    "确认停用此投放": "Deactivate this placement?",
    "停用": "Deactivate",
    "仅显示前": "Only the first",
    "请缩小筛选范围": "Narrow the filters",
    "当前筛选范围内没有生效投放": "No active placements match the current filters",
}

FILES = [
    Path("templates/wagtailadmin/articles/list.html"),
    Path("ai_author_forum/placements/templates/placements/admin/dashboard.html"),
]
for src in FILES:
    text = src.read_text(encoding="utf-8")
    for zh, en in sorted(T.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(zh, en)
    remain = sorted(set(re.findall(r"[\u3400-\u9fff]+", text)))
    if remain:
        raise SystemExit(f"{src}: untranslated: {remain}")
    target = src.with_name(src.stem + ".en" + src.suffix)
    target.write_text(text, encoding="utf-8")
    print(target)
