DEFAULT_LAYOUT_SLOTS = [
    {
        "code": "home_hero",
        "title": "Home hero",
        "scope": "home",
        "max_items": 1,
        "sort_order": 10,
    },
    {
        "code": "home_visual_stories",
        "title": "首页视觉推荐",
        "scope": "home",
        "max_items": 2,
        "sort_order": 20,
    },
    {
        "code": "home_featured",
        "title": "Home featured",
        "scope": "home",
        "max_items": 5,
        "sort_order": 30,
    },
    {
        "code": "latest_ai_article",
        "title": "Latest AI Article",
        "scope": "home",
        "max_items": 8,
        "sort_order": 40,
    },
    {
        "code": "news_block",
        "title": "News block",
        "scope": "section",
        "max_items": 6,
        "sort_order": 40,
    },
    {
        "code": "opinion_block",
        "title": "Opinion block",
        "scope": "section",
        "max_items": 6,
        "sort_order": 50,
    },
    {
        "code": "research_analysis_block",
        "title": "Research Analysis block",
        "scope": "section",
        "max_items": 6,
        "sort_order": 60,
    },
    {
        "code": "journal_highlights",
        "title": "Journal highlights",
        "scope": "journal",
        "max_items": 6,
        "sort_order": 70,
    },
    {
        "code": "journal_hero",
        "title": "Journal hero",
        "scope": "journal",
        "max_items": 1,
        "sort_order": 80,
    },
    {
        "code": "journal_featured",
        "title": "Journal featured",
        "scope": "journal",
        "max_items": 5,
        "sort_order": 90,
    },
    {
        "code": "journal_latest",
        "title": "Journal latest",
        "scope": "journal",
        "max_items": 20,
        "sort_order": 100,
    },
    {
        "code": "section_top_story",
        "title": "Section top story",
        "scope": "section",
        "max_items": 1,
        "sort_order": 110,
    },
    {
        "code": "section_article_list",
        "title": "Section article list",
        "scope": "section",
        "max_items": 20,
        "sort_order": 120,
    },
    {
        "code": "section_sidebar",
        "title": "Section sidebar",
        "scope": "section",
        "max_items": 6,
        "sort_order": 130,
    },
    {
        "code": "search_recommended",
        "title": "Search recommended articles",
        "scope": "search",
        "max_items": 12,
        "sort_order": 140,
    },
    {
        "code": "column_featured",
        "title": "Content column featured",
        "scope": "section",
        "max_items": 1,
        "sort_order": 150,
    },
    {
        "code": "column_secondary",
        "title": "Content column secondary",
        "scope": "section",
        "max_items": 3,
        "sort_order": 155,
    },
    {
        "code": "column_list",
        "title": "Content column article list",
        "scope": "section",
        "max_items": 20,
        "sort_order": 160,
    },
    {
        "code": "column_sidebar",
        "title": "Content column sidebar",
        "scope": "section",
        "max_items": 8,
        "sort_order": 170,
    },
]
