# Generated by Django 6.0.7 on 2026-08-04 08:12

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def backfill_account_identity(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all().iterator():
        updates = []
        if not user.email:
            user.email = f"{user.username}@local.invalid".lower()
            updates.append("email")
        elif user.email != user.email.strip().lower():
            user.email = user.email.strip().lower()
            updates.append("email")
        user.display_name = (
            f"{user.first_name} {user.last_name}".strip() or user.username
        )
        updates.append("display_name")
        if not user.is_active:
            user.account_status = "deactivated"
            user.status_reason = "迁移时账号已停用。"
            updates.extend(["account_status", "status_reason"])
        user.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "正常"),
                    ("suspended", "已暂停"),
                    ("deactivated", "已停用"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="institution",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="status_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.RunPython(backfill_account_identity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="users_user_email_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("account_status", "active"), ("is_active", True)),
                    models.Q(
                        ("account_status__in", ("suspended", "deactivated")),
                        ("is_active", False),
                    ),
                    _connector="OR",
                ),
                name="users_account_status_matches_is_active",
            ),
        ),
    ]
