# Generated by Django 6.0.8 on 2026-08-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_identity_not_empty"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_author",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="作者权限仍需由具体文章的有效投稿关系授予。",
                verbose_name="作者账号",
            ),
        ),
    ]
